### PR TITLE
set default if no value is set for variables which require that

### LINKED ISSUE #48: Errors on site without expected parameters set
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following (and it won't render at all):

```
Building sites … ERROR 2018/03/20 18:40:26 Error while rendering "page" in "": template: /srv/hugo/themes/strata/layouts/_default/single.html:5:5: executing "main" at <partial "post-meta" ...>: error calling partial: template: theme/partials/post-meta.html:2:50: executing "theme/partials/post-meta.html" at <.Site.Params.date_fo...>: invalid value; expected string
ERROR 2018/03/20 18:40:26 Error while rendering "page" in "post/": template: /srv/hugo/themes/strata/layouts/_default/single.html:5:5: executing "main" at <partial "post-meta" ...>: error calling partial: template: theme/partials/post-meta.html:2:50: executing "theme/partials/post-meta.html" at <.Site.Params.date_fo...>: invalid value; expected string
ERROR 2018/03/20 18:40:26 in .Render: Failed to execute template "theme/_default/summary.html": template: theme/_default/summary.html:6:7: executing "theme/_default/summary.html" at <partial "post-meta" ...>: error calling partial: template: theme/partials/post-meta.html:2:50: executing "theme/partials/post-meta.html" at <.Site.Params.date_fo...>: invalid value; expected string
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

ERROR 2018/03/20 18:40:26 Error while rendering "home" in "": template: /srv/hugo/themes/strata/layouts/index.html:15:5: executing "main" at <partial "contact" .>: error calling partial: template: theme/partials/contact.html:8:56: executing "theme/partials/contact.html" at <len .Site.Params.con...>: error calling len: len of untyped nil
```

The reason is likely some absent `.Site.` parameter but you can't tell it from error message, I guess input parameters handling could be improved. https://github.com/cboettig/hugo-now-ui/issues/9 might be used as reference point.

By the way, `Site.Params.dateformat` is used everywhere instead of `Site.Params.date_format`

### PR DESCRIPTION
**Pull request by paskal**
Fix #48.

### CODE REVIEW

**Comment by Hanzei** [comment]
shouldn't this be done for every config settting?

**Comment by paskal** [comment]
Only this one prevent template from rendering, others are just referenced as empty values. Critical things to fix (which I've reported everywhere and fixed here) are variables which are used by some functions and variables with folder names (without which you won't get your static css and js loaded).

**Comment by paskal** [comment]
@digitalcraftsman, any chance this PR will be merged?

**Comment by hanzei** [comment]
Bump

**Pull request closed without merging**
