### PR TITLE
Added Gitlab icon to footer

### PR DESCRIPTION
**Pull request by FISHunderscore**
@digitalcraftsman

### CODE REVIEW

**Comment by FISHunderscore** [comment]
Using this, my build gives the error:
`ERROR: 2017/01/05 20:24:55 general.go:236: theme/partials/footer.html is an incomplete or empty template`

**Comment by FISHunderscore** [comment]
That build error had been fixed.

Now, the site generates and the GitLab icon can be seen in the footer using inspect element, but the icon is not visible.

image

image

In the generated html, it seems that the GitLab icon is missing a ::before.

**Comment by FISHunderscore** [comment]
Both the GitHub and GitLab icons are not present when the project is built and deployed to GitLab Pages. This can be seen [here](https://web.archive.org/web/20170105210203/https://slobotics.gitlab.io/website/).

**Comment by FISHunderscore** [comment]
I believe (but I may be wrong) that @digitalcraftsman needs to update his font awesome config?

**Comment by digitalcraftsman** [comment]
Hello @FISHunderscore,

thanks for your submission. I merged it as 01b840ead26cce003724b82207f557879ddc61f9. In a following commit I updated the version of fontawesome that includes the GitLab icon.

Regards,
Digitalcraftsman

**Pull request closed without merging**
